// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Only used by the Prisma CLI (generate/migrate), never by the running
    // app (see PrismaService, which reads DATABASE_URL directly for its own
    // connection). Must be the direct/non-pooled connection: PgBouncer's
    // transaction-mode pooling can't hold the session-level advisory lock
    // `migrate deploy` needs, which times out with P1002 on the pooled URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
