-- This migration was hand-written instead of generated by `prisma migrate dev`
-- because the dev database currently has unrelated drift versus migration
-- history (pre-existing WIP from other in-progress schema work: NotificationType,
-- Message.offerAmount, Notification.conversationId, Property.city/state/municipality).
-- `prisma migrate dev` refuses to proceed without a destructive `migrate reset`
-- of the shared dev database, so this file was written by hand and applied with
-- `prisma migrate deploy` (which does not diff/reset, it just runs pending
-- migration files in order), then recorded via `prisma migrate resolve --applied`.

-- AlterTable: add firstName/lastName as nullable first, backfill, then enforce NOT NULL
ALTER TABLE "User" ADD COLUMN "firstName" TEXT;
ALTER TABLE "User" ADD COLUMN "lastName" TEXT;

-- Backfill firstName/lastName by splitting the existing "name" value on the
-- first space: everything before the first space becomes firstName, everything
-- after becomes lastName. Fallback when there is no space in "name": the whole
-- name goes into firstName and lastName is set to a single space (" ") rather
-- than duplicating the full name into both columns.
UPDATE "User"
SET
  "firstName" = CASE
    WHEN position(' ' IN "name") > 0 THEN substring("name" FROM 1 FOR position(' ' IN "name") - 1)
    ELSE "name"
  END,
  "lastName" = CASE
    WHEN position(' ' IN "name") > 0 THEN substring("name" FROM position(' ' IN "name") + 1)
    ELSE ' '
  END
WHERE "firstName" IS NULL OR "lastName" IS NULL;

-- Last-resort safety net for any row that still ended up NULL (e.g. NULL "name",
-- which the schema does not otherwise allow, but we guard for it anyway).
UPDATE "User" SET "firstName" = '' WHERE "firstName" IS NULL;
UPDATE "User" SET "lastName" = '' WHERE "lastName" IS NULL;

ALTER TABLE "User" ALTER COLUMN "firstName" SET NOT NULL;
ALTER TABLE "User" ALTER COLUMN "lastName" SET NOT NULL;

-- Rename showPhoneOnListings -> showWhatsapp, preserving existing data.
ALTER TABLE "User" RENAME COLUMN "showPhoneOnListings" TO "showWhatsapp";
